version: '3.8'
services:
  # mysql:
  #   image: mysql:8.0.34
  #   container_name: mysql.service.com
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #   ports:
  #     - '3306:3306'

  hororok-app:
    image: changwoot/hororok-app:latest
    build:
      context: .
      dockerfile: DockerFile.hororok-app
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_PORT: ${MONGODB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      SERVER_PORT: ${SERVER_PORT}
    restart: always

  timer-app:
    image: changwoot/timer-app:latest
    build:
      context: .
      dockerfile: DockerFile.timer-app
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_PORT: ${MONGODB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      SERVER_PORT: ${SERVER_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    restart: always

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    container_name: web.server.com
    depends_on:
      - hororok-app
      - timer-app
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
