# Base image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN yarn install

# Bundle app source
COPY . .

# Creates a "dist" folder with the production build
RUN yarn build

# Install PM2 globally
RUN yarn global add pm2

# Copy ecosystem config
COPY ecosystem.config.js .

# Start the applications using PM2
CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
