name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull changwoot/hororok-api:latest
      - name: Delete Old docker container
        run: sudo docker rm -f hororok-api-container || true
      - name: Run Docker Container
        run: |
          sudo docker run -d -p 80:4000 \
          -e MONGODB_URL=${{ secrets.MONGODB_URL }} \
          -e MONGODB_PORT=${{ secrets.MONGODB_PORT }} \
          -e PORT=${{ secrets.PORT }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
          --name hororok-api-container changwoot/hororok-api
