name: CI/CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: 'yarn'

      - name: Create .env.test file
        run: |
          sudo rm -rf .env.test
          echo "${{ secrets.ENV_TEST }}" >> .env.test

      - name: Install Dependencies
        run: yarn install

      - name: Install Redis And Start
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          sudo service redis-server start

      - name: Run Tests
        run: yarn test:e2e

      - name: Stop Redis Server
        run: redis-cli shutdown

  build:
    needs: test-e2e
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create .env.prod file
        run: |
          sudo rm -rf .env.prod
          echo "${{ secrets.ENV_PROD }}" >> .env.prod

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Compose Services
        run: docker-compose build --no-cache
      - name: Push Docker Compose Images
        run: docker-compose push

  deploy:
    needs: build
    runs-on: [self-hosted, 'hororok']
    steps:
      # ###### 필요할때만 활성화 (파일전송시 ec2 폴더 초기화됨 (인증서 사라짐)) ######
      # ########### docker-compose.yml, nginx.conf 수정시엔 ec2 직접가서 수정)
      # - uses: actions/checkout@v3
      #############################
      - name: Create .env.prod file
        run: |
          sudo rm -rf .env.prod
          echo "${{ secrets.ENV_PROD }}" >> .env.prod

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Deploy
        run: |
          CONTAINERS=$(docker ps -qa)
          if [ -n "$CONTAINERS" ]; then
            sudo docker rm -f $CONTAINERS
          fi
          sudo docker-compose pull
          docker-compose up -d
          docker image prune -f
